---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatchtower-config-cronjob
  namespace: kubewatchtower
data:
  run-once: "true"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubewatchtower
  namespace: kubewatchtower
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kubewatchtower
        spec:
          serviceAccountName: kubewatchtower
          restartPolicy: OnFailure
          containers:
            - name: kubewatchtower
              image: kubewatchtower:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: kubewatchtower-config-cronjob
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL

