---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-watchtower

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-watchtower-config
  namespace: kube-watchtower
data:
  # Namespace filtering (choose one mode):
  # Whitelist mode: Only monitor specified namespaces (recommended for production)
  ENABLE_NAMESPACES: ""  # Example: "production,staging"
  # Blacklist mode: Monitor all namespaces except specified ones (used when ENABLE_NAMESPACES is empty)
  DISABLE_NAMESPACES: "kube-system,kube-public"  # Example: "kube-system,kube-public,default"
  
  # Notification settings
  NOTIFICATION_URL: ""
  NOTIFICATION_CLUSTER: "kubernetes"
  
  # Operation mode
  DRY_RUN: "false"  # Enable dry-run mode (detect but not update)
  
  # Timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "Asia/Shanghai"

  # Log level (debug, info, warn, error)
  LOG_LEVEL: "debug"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-watchtower
  namespace: kube-watchtower

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-watchtower
rules:
  # check and rollout Workload（Deployment / StatefulSet / DaemonSet）
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - patch
      - update

  # check Pods（check digest and rollout status）
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  # check imagePullSecrets
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-watchtower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-watchtower
subjects:
  - kind: ServiceAccount
    name: kube-watchtower
    namespace: kube-watchtower

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-watchtower
  namespace: kube-watchtower
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-watchtower
          restartPolicy: Never
          containers:
            - name: kube-watchtower
              image: ghcr.io/qetesh/kube-watchtower:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: kube-watchtower-config